apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: henius-ingress
  namespace: henius
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    # Game client (web app)
    - host: henius.84.247.165.145.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game
                port:
                  number: 80
    # Colyseus game server (WebSocket)
    - host: server.84.247.165.145.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 2567
